### ISSUE TITLE
이렇게 해 보는 것은 어떨까

### ISSUE THREAD

**Issue by Gumball12** [ycj1212/CoreJava#1]
다음과 같이 작성해 보는 것은 어떨까.

```md
# 5. 상속 (Inheritance)
4장에서 클래스와...

## 5-1 클래스, 부모클래스(Superclass), 자식클래스(Subclass)
우리가 이전 장에서 다루던...

### 5-1-1 자식클래스 정의
당신이 Employee 클래스로부터...

### 5-1-2 메소드 오버라이딩
슈퍼클래스 메소드의 몇몇은...
```

이는 실제로 다음과 같이 보여지고,

---

# 5. 상속 (Inheritance)
4장에서 클래스와...

## 5-1 클래스, 부모클래스(Superclass), 자식클래스(Subclass)
우리가 이전 장에서 다루던...

### 5-1-1 자식클래스 정의
당신이 Employee 클래스로부터...

### 5-1-2 메소드 오버라이딩
슈퍼클래스 메소드의 몇몇은...

---

이를 통해 나중에 너나, 아니면 다른 사람이 이 글을 읽었을 때, 좀 더 보기 쉬운 글을 작성할 수 있게 되리라 생각함. 적어도 지금보다는

**Comment by ycj1212** [comment]
Ok, I`ll try that. Thank you for giving me advice.

**Comment by Gumball12** [comment]
your welcome 🙃
